// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fue")>]
[<assembly: AssemblyProductAttribute("Fue")>]
[<assembly: AssemblyDescriptionAttribute("F# templating library")>]
[<assembly: AssemblyVersionAttribute("0.3.0")>]
[<assembly: AssemblyFileVersionAttribute("0.3.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fue"
    let [<Literal>] AssemblyProduct = "Fue"
    let [<Literal>] AssemblyDescription = "F# templating library"
    let [<Literal>] AssemblyVersion = "0.3.0"
    let [<Literal>] AssemblyFileVersion = "0.3.0"
